version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clp_dev
    volumes:
      - ./db:/var/lib/postgresql
    ports:
      - "5432:5432"